# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DynaPage-Document
version:      0.90
version_from: Document.pm
installdirs:  site
requires:
    DynaPage::Document::ext::include: 0
    strict:                        0
    Test::Easy:                    1.01
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
