#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	DynaPage::Document;
	use DynaPage::Document::ext::include;
	
	print "START\n";
	
	my	$opt	= 
	{
		RootDir			=> '.',
		Document		=> 'document.dpd',
		
	};
	
	my	$dpd	= DynaPage::Document->new( $opt );
	
	print "PARSED\n";
	
	print pp($dpd);